# ===================================================================
# H2 DATABASE CONFIGURATION
# ===================================================================

# H2 Console Settings
# Enable the H2 database console, accessible at /h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# DataSource Settings for File-based H2 Database
# The URL specifies that the database should be stored in a file.
spring.datasource.url=jdbc:h2:mem:soko
spring.datasource.username=user
spring.datasource.password=

# Application Settings
spring.application.name=soko
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
server.port=8081
